name: release-jetbrains
on:
  push:
    tags:
      - "jetbrains/v*"

permissions:
  contents: write

jobs:
  release-jetbrains:
    name: release JetBrains plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set up Java environment for the next steps
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      # Setup Gradle
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      # Publish the plugin to JetBrains Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.JET_BRAINS_PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
        working-directory: ./lsp/client/jetbrains

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $GITHUB_REF_NAME ./build/distributions/*
        working-directory: ./lsp/client/jetbrains
